language: python
python:
  - 2.7
install:
  - pip install flake8
  - python setup.py install
  - pip install psycopg2
script:
  - python setup.py test
  - python setup.py test_on_postgres
  - flake8 .
notifications:
  email:
  - ci-notify@openlabs.co.in